#!/usr/bin/env python3
"""Extract candidate icon images from the PDF and build initial symbol catalog.

Scans the PDF for small images (likely inline game icons),
extracts them, deduplicates by perceptual similarity, and writes
template PNGs + a catalog TOML skeleton.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import cv2
import fitz
import numpy as np

PDF_PATH = Path("materials/ATO_CORE_Rulebook_v1.1.pdf")
OUTPUT_DIR = Path("configs/symbols/templates")
CATALOG_PATH = Path("configs/symbols/ato_core_v1_1.symbols.toml")

# Images with max dimension <= this are icon candidates
MAX_ICON_DIM = 80
MIN_ICON_DIM = 10


def extract_icon_candidates() -> list[dict[str, object]]:
    """Extract small images from the PDF as icon candidates."""
    doc = fitz.open(str(PDF_PATH))
    candidates: list[dict[str, object]] = []
    seen_hashes: set[str] = set()

    for pn in range(len(doc)):
        page = doc[pn]
        page_id = f"p{pn + 1:04d}"

        for img_info in page.get_images(full=True):
            xref = img_info[0]
            w, h = img_info[2], img_info[3]

            if max(w, h) > MAX_ICON_DIM or min(w, h) < MIN_ICON_DIM:
                continue

            # Skip 1x1 spacer images
            if w <= 2 or h <= 2:
                continue

            try:
                img_data = doc.extract_image(xref)
                if not img_data:
                    continue

                raw = img_data["image"]
                img_hash = hashlib.sha256(raw).hexdigest()[:16]

                if img_hash in seen_hashes:
                    continue
                seen_hashes.add(img_hash)

                # Get placement rect
                rects = page.get_image_rects(xref)
                rect = rects[0] if rects else None

                candidates.append({
                    "xref": xref,
                    "width": w,
                    "height": h,
                    "hash": img_hash,
                    "page_id": page_id,
                    "page_number": pn + 1,
                    "rect": [rect.x0, rect.y0, rect.x1, rect.y1] if rect else None,
                    "image_bytes": raw,
                    "ext": img_data.get("ext", "png"),
                })
            except Exception:
                pass

    doc.close()
    return candidates


def save_templates(candidates: list[dict[str, object]]) -> list[dict[str, str]]:
    """Save unique icon candidate images as template PNGs."""
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    saved: list[dict[str, str]] = []

    for i, c in enumerate(candidates):
        filename = f"icon_{i:03d}_{c['width']}x{c['height']}_{c['hash']}.png"
        path = OUTPUT_DIR / filename

        raw = c["image_bytes"]
        assert isinstance(raw, bytes)

        # Convert to PNG if needed
        nparr = np.frombuffer(raw, np.uint8)
        img = cv2.imdecode(nparr, cv2.IMREAD_UNCHANGED)
        if img is not None:
            cv2.imwrite(str(path), img)
            saved.append({
                "filename": filename,
                "width": str(c["width"]),
                "height": str(c["height"]),
                "hash": str(c["hash"]),
                "first_page": str(c["page_id"]),
            })

    return saved


def write_catalog_skeleton(saved: list[dict[str, str]]) -> None:
    """Write a TOML catalog skeleton for manual labeling."""
    lines = [
        "# Symbol catalog for ATO Core Rulebook v1.1",
        "# Generated by scripts/import_symbol_catalog.py — review and label manually.",
        "",
        'catalog_id = "ato_core_v1_1"',
        'version = "1.0"',
        "",
    ]

    for s in saved:
        lines.extend([
            "[[symbols]]",
            f'symbol_id = "sym.unknown_{s["hash"][:8]}"',
            'label = ""  # TODO: label this icon',
            'alt_label_ru = ""',
            f'template_asset = "configs/symbols/templates/{s["filename"]}"',
            "match_threshold = 0.85",
            "inline = true",
            f'# first seen: {s["first_page"]}, {s["width"]}x{s["height"]}px',
            "",
        ])

    CATALOG_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    print("Extracting icon candidates from PDF...")
    candidates = extract_icon_candidates()
    print(f"  Found {len(candidates)} unique small images")

    print("Saving template images...")
    saved = save_templates(candidates)
    print(f"  Saved {len(saved)} templates to {OUTPUT_DIR}")

    print("Writing catalog skeleton...")
    write_catalog_skeleton(saved)
    print(f"  Wrote {CATALOG_PATH}")

    # Summary
    print("\nIcon candidate summary:")
    for s in saved:
        print(f"  {s['filename']} ({s['width']}x{s['height']}px, first on {s['first_page']})")


if __name__ == "__main__":
    main()
